package com.indagalab.agentos.ui.pixel

import androidx.compose.ui.graphics.Color

/**
 * El arte de la sala, escrito como texto.
 *
 * Convención de caracteres:
 *   .  transparente      O  contorno (negro)     S  piel
 *   H  pelo              C  camiseta (color del skill)
 *   P  pantalón          B  zapatos              E  blanco del ojo
 *   D  madera oscura     W  madera clara         G  pantalla/cristal
 *   L  luz / brillo      A  acento (naranja Indaga)
 *
 * El color de camiseta NO está fijado aquí: `personaje(color)` lo inyecta, así
 * cada skill tiene el suyo sin duplicar el arte.
 */

private val NEGRO = Color(0xFF14110F)
private val PIEL = Color(0xFFE8B48C)
private val PIEL_OSC = Color(0xFFC98F66)
private val PELO = Color(0xFF3A2A1E)
private val PANTALON = Color(0xFF3D4B63)
private val ZAPATO = Color(0xFF241C16)
private val BLANCO = Color(0xFFF6EFE6)
private val MADERA = Color(0xFF6B4A2F)
private val MADERA_CLARA = Color(0xFF8C6440)
private val PANTALLA = Color(0xFF1E3A44)
private val BRILLO = Color(0xFF7FD4E8)
private val NARANJA = Color(0xFFF97316)

private val SILLA = Color(0xFF3E4A57)
private val LAPTOP_TAPA = Color(0xFFB9C2CC)
private val LAPTOP_PANTALLA = Color(0xFF2E5F73)
private val APAGADO = Color(0xFF4A423C)
private val OJO = Color(0xFF241C16)

/** Oscurece un color para usarlo como sombra. */
private fun Color.sombra(f: Float = 0.72f) = Color(red * f, green * f, blue * f, alpha)

private fun paletaPersonaje(
    camiseta: Color,
    piel: Color = PIEL,
    pelo: Color = PELO,
) = mapOf(
    'o' to NEGRO,          // contorno: solo la silueta exterior
    'O' to NEGRO,
    'H' to pelo,
    'S' to piel,
    's' to piel.sombra(0.82f),       // sombra de piel: da volumen a la cara
    'E' to OJO,
    'C' to camiseta,
    'c' to camiseta.sombra(),
    'R' to SILLA,
    'L' to LAPTOP_TAPA,
    'G' to LAPTOP_PANTALLA,
    'P' to PANTALON,
    'B' to ZAPATO,
    'X' to APAGADO,        // todo lo que está fuera de servicio
)

// Puesto completo: silla + persona + portátil, en un solo sprite de 22×26.
// Antes el personaje y el escritorio iban por separado y se pisaban; y el
// contorno negro rodeaba cada parte, lo que los volvía manchas. Ahora el
// contorno es solo la silueta exterior y cada color lleva su tono de sombra.

// ── Sentado tecleando, frame A (manos sobre el teclado) ─────────────────────
private const val WORK_A = """
......................
........oooooo........
.......oHHHHHHo.......
......oHHHHHHHHo......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSsso......
.......oSSSSSSo.......
........oSSSSo........
.....ooooCCCCoooo.....
....oRRoCCCCCCoRRo....
....oRRoCCCCCCoRRo....
....oRRoCCCCCCoRRo....
....oRRoSCCCCSoRRo....
....oRRooooooooRRo....
....oRRRRRRRRRRRRo....
.....oooooooooooo.....
......oLLLLLLLLo......
.....oLLLLLLLLLLo.....
.....oGGGGGGGGGGo.....
......oooooooooo......
........oPPPPo........
........oPooPo........
.......oBBooBBo.......
........oooooo........
"""

// ── Sentado tecleando, frame B (manos levantadas) ───────────────────────────
private const val WORK_B = """
......................
........oooooo........
.......oHHHHHHo.......
......oHHHHHHHHo......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSsso......
.......oSSSSSSo.......
........oSSSSo........
.....ooooCCCCoooo.....
....oRRoCCCCCCoRRo....
....oRRSCCCCCCSRRo....
....oRRoCCCCCCoRRo....
....oRRoCCCCCCoRRo....
....oRRooooooooRRo....
....oRRRRRRRRRRRRo....
.....oooooooooooo.....
......oLLLLLLLLo......
.....oLLLLLLLLLLo.....
.....oGGGGGGGGGGo.....
......oooooooooo......
........oPPPPo........
........oPooPo........
.......oBBooBBo.......
........oooooo........
"""

// ── Dormido: cabeza caída sobre el portátil ─────────────────────────────────
private const val SLEEP = """
......................
......................
......................
......................
......................
......................
.......oooooooo.......
......oHHHHHHHHo......
.....oHHHHHHHHHHo.....
.....oHSSSSSSSSHo.....
.....ooooSSSSoooo.....
....oRRoCCCCCCoRRo....
....oRRoCCCCCCoRRo....
....oRRoCCCCCCoRRo....
....oRRoCCCCCCoRRo....
....oRRooooooooRRo....
....oRRRRRRRRRRRRo....
.....oooooooooooo.....
......oLLLLLLLLo......
.....oLLLLLLLLLLo.....
.....oGGGGGGGGGGo.....
......oooooooooo......
........oPPPPo........
........oPooPo........
.......oBBooBBo.......
........oooooo........
"""

// ── Fuera de servicio: silla vacía y portátil apagado ───────────────────────
private const val DEAD = """
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
.....oooooooooooo.....
....oRRoooooooooRo....
....oRRoXXXXXXooRo....
....oRRoXXXXXXooRo....
....oRRoXXXXXXooRo....
....oRRooooooooRRo....
....oRRRRRRRRRRRRo....
.....oooooooooooo.....
......oLLLLLLLLo......
.....oLLLLLLLLLLo.....
.....oXXXXXXXXXXo.....
......oooooooooo......
........oXXXXo........
........oXooXo........
.......oXXooXXo.......
........oooooo........
"""

// ── De pie / caminando (sin silla): dos frames ──────────────────────────────
private const val WALK_A = """
......................
........oooooo........
.......oHHHHHHo.......
......oHHHHHHHHo......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSsso......
.......oSSSSSSo.......
........oSSSSo........
.......oCCCCCCo.......
......oCCCCCCCCo......
.....oSCCCCCCCCo......
.....oSoCCCCCCoSo.....
......ooCCCCCCoSo.....
.......oCCCCCCo.......
.......oPPPPPPo.......
.......oPPooPPo.......
......oPPo..oPPo......
......oPo....oPo......
.....oBBo....oBo......
.....ooo......ooo.....
......................
......................
......................
......................
"""

private const val WALK_B = """
......................
........oooooo........
.......oHHHHHHo.......
......oHHHHHHHHo......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSsso......
.......oSSSSSSo.......
........oSSSSo........
.......oCCCCCCo.......
......oCCCCCCCCo......
......oCCCCCCCCSo.....
.....oSoCCCCCCoSo.....
.....oSoCCCCCCoo......
.......oCCCCCCo.......
.......oPPPPPPo.......
.......oPPooPPo.......
.......oPPooPPo.......
.......oPo..oPo.......
.......oBo..oBBo......
......ooo....ooo......
......................
......................
......................
......................
"""

// Alias: de pie quieto = primer frame de caminar
private const val IDLE = WALK_A

// ── Mobiliario ──────────────────────────────────────────────────────────────
private const val ESCRITORIO = """
OOOOOOOOOOOOOOOO
OWWWWWWWWWWWWWWO
OWWWWWWWWWWWWWWO
ODDDDDDDDDDDDDDO
OD............DO
OD............DO
OD............DO
OOD..........DOO
.OD..........DO.
.OO..........OO.
"""

// El robot de AgentOS, el mismo de la app, en pixel art. Preside la sala
// desde el fondo: es el jefe de todos estos.
private const val ROBOT = """
.......oo.......
.......oo.......
......oAAo......
...oooooooooo...
..oAAAAAAAAAAo..
..oAoEEooEEoAo..
..oAoEEooEEoAo..
..oAAAAAAAAAAo..
..oAAooooooAAo..
..oAAAAAAAAAAo..
...oooooooooo...
..oo.oAAAAo.oo..
..oAooAAAAooAo..
..oAAoAAAAoAAo..
...oo.oAAo.oo...
......oooo......
"""

private const val MONITOR = """
OOOOOOOOOOOOOOOOOO
OGGGGGGGGGGGGGGGGO
OGLLGGGGGGGGGGLLGO
OGGGGGGGGGGGGGGGGO
OGGLLLLGGGGLLLLGGO
OGGGGGGGGGGGGGGGGO
OGLLGGGGGGGGGGLLGO
OGGGGGGGGGGGGGGGGO
OGGGGLLLLLLGGGGGGO
OGGGGGGGGGGGGGGGGO
OOOOOOOOOOOOOOOOOO
.....OOOOOOOO.....
.......OOOO.......
.....OOOOOOOO.....
"""

// ── Mobiliario de oficina ───────────────────────────────────────────────────

/** Planta en maceta: lo primero que tiene cualquier oficina de verdad. */
private const val PLANTA = """
......oo......
....ooVVoo....
...oVVVVVVo...
..oVVoVVoVVo..
.oVVooVVooVVo.
.oVVoVVVVoVVo.
..oVVVVVVVVo..
...ooVVVVoo...
.....oVVo.....
.....oVVo.....
....oooooo....
....oTTTTo....
....oTTTTo....
...oTTTTTTo...
...oooooooo...
"""

/** Rack de servidores: el "OS" de AgentOS, con sus luces parpadeando. */
private const val RACK = """
oooooooooooo
oMMMMMMMMMMo
oMoooooooeMo
oMoLLLLLLoMo
oMoooooooeMo
oMoLLLLLLoMo
oMoooooooeMo
oMoLLLLLLoMo
oMoooooooeMo
oMoLLLLLLoMo
oMoooooooeMo
oMMMMMMMMMMo
oooooooooooo
.oo......oo.
"""

/** Máquina de café. La oficina sin café no es oficina. */
private const val CAFE = """
..oooooooo..
.oMMMMMMMMo.
.oMoooooeMo.
.oMoGGGGoMo.
.oMoGGGGoMo.
.oMoooooeMo.
.oMMMMMMMMo.
.oMoWWWWoMo.
.oMoWWWWoMo.
.oMMMMMMMMo.
..oooooooo..
..oo....oo..
"""

/** Pizarra con un gráfico que sube. Optimismo de oficina. */
private const val PIZARRA = """
oooooooooooooooo
oWWWWWWWWWWWWWWo
oWWWWWWWWWWWAAWo
oWWWWWWWWWAAWWWo
oWWWWWWWAAWWWWWo
oWWWWWAAWWWWWWWo
oWWWAAWWWWWWWWWo
oWAAWWWWWWWWWWWo
oWWWWWWWWWWWWWWo
oooooooooooooooo
....oo....oo....
....oo....oo....
"""

// ── Zona de descanso ────────────────────────────────────────────────────────

/** Máquina arcade. El motivo por el que nadie vuelve del descanso. */
private const val ARCADE = """
.oooooooooo.
.oMMMMMMMMo.
.oMpppppp Mo
.oMpAApAApMo
.oMppppppMo.
.oMpAAAAApMo
.oMpppppp Mo
.oMMMMMMMMo.
.oMLLoLLoMo.
.oMMMMMMMMo.
.oMoooooeMo.
.oMeeeeeeMo.
.oMMMMMMMMo.
..oo....oo..
"""

/** Sofá. Dos plazas, tapizado rojo, un poco hundido. */
private const val SOFA = """
oooooooooooooooooo
oRRRRoooooooRRRRRo
oRrrRoRRRRRoRrrrRo
oRrrRoRrrrRoRrrrRo
oRRRRoRrrrRoRRRRRo
oRRRRRRRRRRRRRRRRo
oRrrrrrrrrrrrrrrRo
oRRRRRRRRRRRRRRRRo
ooooooooooooooooo.
.oo..........oo...
.oo..........oo...
"""

/** Tele con una partida en marcha. */
private const val TELE = """
oooooooooooooooo
oMMMMMMMMMMMMMMo
oMGGGGGGGGGGGGMo
oMGGpppGGGpppGMo
oMGGpAApGGpAApGo
oMGGpppGGGpppGMo
oMGGGGGGGGGGGGMo
oMGGGAAAAAAGGGMo
oMMMMMMMMMMMMMMo
oooooooooooooooo
.....oooooo.....
....oooooooo....
"""

/** Nevera de cervezas. La recompensa por acabar el turno. */
private const val NEVERA = """
.oooooooooo.
.oMMMMMMMMo.
.oMGGGGGGMo.
.oMGvbvbGMo.
.oMGvvvvGMo.
.oMGGGGGGMo.
.oMMMMMMMMo.
.oMGGGGGGMo.
.oMGvbvbGMo.
.oMGvvvvGMo.
.oMGGGGGGMo.
.oMMMMMMMMo.
.oMoooooeMo.
.oMMMMMMMMo.
..oo....oo..
"""

/** Mesa baja con dos jarras. */
private const val MESA_OCIO = """
oooooooooooo
ommmmmmmmmmo
omvbmmmmvbmo
omvvmmmmvvmo
ommmmmmmmmmo
oooooooooooo
..oo....oo..
..oo....oo..
"""

/** Tumbona con toalla. */
private const val TUMBONA = """
....oooooooo
...oyyyyyyyo
..oyyyyyyyo.
.omoooooomo.
omooooooomo.
.oo......oo.
"""

/** Sombrilla. */
private const val SOMBRILLA = """
....oooo....
..ooAAAAoo..
.oAAAAAAAAo.
oAAAAAAAAAAo
.oooomooooo.
.....mo.....
.....mo.....
.....mo.....
....oooo....
"""

/** Flotador en el agua. */
private const val FLOTADOR = """
..oooooo..
.oAAAAAAo.
oAAWWWWAAo
oAWWaaWWAo
oAWWaaWWAo
oAAWWWWAAo
.oAAAAAAo.
..oooooo..
"""

/** Bailando, brazo derecho arriba. */
private const val BAILA_A = """
......................
..........oo..........
........ooHHoo........
.......oHHHHHHo.......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSsso......
.......oSSSSSSo.......
...oSo..oSSSSo........
...oSo.oCCCCCCo.......
...oSooCCCCCCCCo......
....ooCCCCCCCCCoSo....
.......oCCCCCCooSo....
.......oCCCCCCoooo....
.......oPPPPPPo.......
.......oPPooPPo.......
......oPPo..oPPo......
.....oPPo....oPo......
.....oBBo....oBo......
.....ooo......ooo.....
......................
......................
......................
......................
......................
"""

/** Bailando, el otro brazo arriba y la cadera al otro lado. */
private const val BAILA_B = """
......................
..........oo..........
........ooHHoo........
.......oHHHHHHo.......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSsso......
.......oSSSSSSo.......
........oSSSSo..oSo...
.......oCCCCCCo.oSo...
......oCCCCCCCCooSo...
....oSoCCCCCCCCCoo....
....oSooCCCCCCo.......
....oooCCCCCCo........
.......oPPPPPPo.......
.......oPPooPPo.......
......oPPo..oPPo......
......oPo....oPPo.....
......oBo....oBBo.....
.....ooo......ooo.....
......................
......................
......................
......................
......................
"""

/** Bola de discoteca. Cuelga del techo de la sala de descanso. */
private const val BOLA = """
.....oooo.....
....oMMMMo....
...oMLMMLMo...
..oMMLMMLMMo..
..oLMMLMMLMo..
..oMMLMMLMMo..
...oMLMMLMo...
....oMMMMo....
.....oooo.....
"""

/** Cabina de baño con la puerta cerrada. */
private const val CABINA = """
oooooooooooo
oMMMMMMMMMMo
oMeeeeeeeeMo
oMeeeeeeeeMo
oMeeeeeoeeMo
oMeeeeeeeeMo
oMeeeeeeeeMo
oMeeeeeeeeMo
oMMMMMMMMMMo
oooooooooooo
.oo......oo.
"""

/** Lavabo con espejo. */
private const val LAVABO = """
oooooooooo
oGGGGGGGGo
oGGGGGGGGo
oooooooooo
.oBBBBBBo.
.oBBBBBBo.
.oBBeeBBo.
.ooBBBBoo.
...oMMo...
...oMMo...
..oooooo..
"""

/** Estantería con carpetas. Oficina de las de verdad. */
private const val ESTANTERIA = """
oooooooooooo
oAAoAAoAAoAo
oAAoAAoAAoAo
oooooooooooo
oWWoWWoWWoWo
oWWoWWoWWoWo
oooooooooooo
oAAoWWoAAoWo
oAAoWWoAAoWo
oooooooooooo
.oo......oo.
"""

/** Reloj de pared. Marca la hora a la que nadie mira. */
private const val RELOJ = """
..oooooo..
.oWWWWWWo.
oWWWoWWWWo
oWWWoWWWWo
oWWWoooWWo
oWWWWWWWWo
oWWWWWWWWo
.oWWWWWWo.
..oooooo..
"""

// ── Iconos de burbuja (8×8) ─────────────────────────────────────────────────
private const val ICO_IDEA = """
..OOOO..
.OLLLLO.
.OLLLLO.
.OLLLLO.
..OLLO..
..OOOO..
...OO...
...OO...
"""

private const val ICO_ZZZ = """
.OOOOO..
....OO..
...OO...
..OO....
.OOOOO..
........
..OOOO..
....OO..
"""

private const val ICO_CHAT = """
.OOOOOO.
OLLLLLLO
OLOLOLLO
OLLLLLLO
OLLLLLLO
.OOOOOO.
..OO....
.OO.....
"""

private const val ICO_ERROR = """
.OO..OO.
OLLOOLLO
.OLLLLO.
..OLLO..
..OLLO..
.OLLLLO.
OLLOOLLO
.OO..OO.
"""

// ── Fábricas ────────────────────────────────────────────────────────────────

/** Frames de un personaje con el color de camiseta dado. */
// ── Personaje fuera de la oficina ───────────────────────────────────────────
// Mismo cuerpo de 22×26 que el resto, para que encaje en la misma rejilla.

/** De pie, brazos hacia el mando. Frente a la máquina arcade. */
private const val JUEGA_A = """
......................
........oooooo........
.......oHHHHHHo.......
......oHHHHHHHHo......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSsso......
.......oSSSSSSo.......
........oSSSSo........
....oooCCCCCCooo......
...oSSoCCCCCCoSSo.....
...oSSoCCCCCCoSSo.....
....ooCCCCCCCCoo......
.......oCCCCCCo.......
.......oCCCCCCo.......
.......oPPPPPPo.......
.......oPPooPPo.......
......oPPo..oPPo......
......oPo....oPo......
.....oBBo....oBBo.....
.....ooo......ooo.....
......................
......................
......................
......................
"""

/** El mismo, con los brazos un pixel más arriba. La partida va bien. */
private const val JUEGA_B = """
......................
........oooooo........
.......oHHHHHHo.......
......oHHHHHHHHo......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSsso......
.......oSSSSSSo.......
...oSSo.oSSSSo.oSSo...
...oSSoCCCCCCooSSo....
....ooCCCCCCCCoo......
.......oCCCCCCo.......
.......oCCCCCCo.......
.......oCCCCCCo.......
.......oCCCCCCo.......
.......oPPPPPPo.......
.......oPPooPPo.......
......oPPo..oPPo......
......oPo....oPo......
.....oBBo....oBBo.....
.....ooo......ooo.....
......................
......................
......................
......................
"""

/** Tumbado boca arriba, cabeza en el reposabrazos y piernas cruzadas. */
private const val TUMBADO = """
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
....oooo..............
...oHHHHo.............
..oHHSSSHo..ooooooo...
..oHSSSSSooCCCCCCCoo..
..oSEsSSSoCCCCCCCCCPo.
..oSSSSSSoCCCCCCCCPPo.
..oSsSSSSoCCCCCCCoPPPo
...oSSSSooooooooooPPo.
....oooo........oBBBo.
.................ooo..
......................
"""

/** En el agua: sólo asoman cabeza y hombros. */
private const val NADA_A = """
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
........oooooo........
.......oHHHHHHo.......
......oHHHHHHHHo......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
.....ooSsSSSSssoo.....
....oSSoSSSSSSoSSo....
....oSSoCCCCCCoSSo....
.....ooCCCCCCCCoo.....
......................
......................
......................
"""

/** Brazada. El otro brazo fuera. */
private const val NADA_B = """
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
......................
....oSSo..............
....oSSo.oooooo.......
.....oo.oHHHHHHo......
......oHHHHHHHHo......
......oHSSSSSSHo......
......oSSEsSEsSo......
......oSSSSSSSSo......
......oSsSSSSssoo.....
.......oSSSSSSoSSo....
.......oCCCCCCoSSo....
......oCCCCCCCCoo.....
......................
......................
......................
"""

class Personaje(
    camiseta: Color,
    piel: Color = PIEL,
    pelo: Color = PELO,
) {
    private val pal = paletaPersonaje(camiseta, piel, pelo)
    val idle = PixelSprite.of(IDLE, pal)
    val walkA = PixelSprite.of(WALK_A, pal)
    val walkB = PixelSprite.of(WALK_B, pal)
    val workA = PixelSprite.of(WORK_A, pal)
    val workB = PixelSprite.of(WORK_B, pal)
    val sleep = PixelSprite.of(SLEEP, pal)
    val dead = PixelSprite.of(DEAD, pal)
    // Fuera de la oficina cada uno hace algo distinto: verlos a todos en la
    // misma postura era lo que hacía que la sala de descanso pareciera un
    // error de dibujado y no un sitio donde pasa algo.
    val juegaA = PixelSprite.of(JUEGA_A, pal)
    val juegaB = PixelSprite.of(JUEGA_B, pal)
    val tumbado = PixelSprite.of(TUMBADO, pal)
    val nadaA = PixelSprite.of(NADA_A, pal)
    val nadaB = PixelSprite.of(NADA_B, pal)
    val bailaA = PixelSprite.of(BAILA_A, pal)
    val bailaB = PixelSprite.of(BAILA_B, pal)
}

private val palMobiliario = mapOf(
    'O' to NEGRO, 'D' to MADERA, 'W' to MADERA_CLARA,
    'G' to PANTALLA, 'L' to BRILLO,
)

val SPRITE_ESCRITORIO by lazy { PixelSprite.of(ESCRITORIO, palMobiliario) }
val SPRITE_MONITOR by lazy { PixelSprite.of(MONITOR, palMobiliario) }

/** El robot de marca. 'A' es el naranja Indaga; 'E', sus ojos. */
val SPRITE_ROBOT by lazy {
    PixelSprite.of(ROBOT, mapOf(
        'o' to NEGRO, 'O' to NEGRO,
        'A' to NARANJA,
        'E' to Color(0xFF2A1508),
    ))
}

// Mobiliario: metal frío para el rack y la cafetera, verde para la planta.
private val palOficina = mapOf(
    'o' to NEGRO, 'O' to NEGRO,
    'V' to Color(0xFF4E8C5A),          // hoja
    'T' to Color(0xFFB5653C),          // maceta de barro
    'M' to Color(0xFF4A5560),          // metal
    'L' to Color(0xFF7FD4E8),          // LED encendido
    'e' to Color(0xFF2A3138),          // hueco/sombra
    'G' to Color(0xFF2E5F73),          // cristal
    'W' to Color(0xFFE6DCCF),          // blanco hueso
    'A' to NARANJA,
    'R' to Color(0xFF8C3F3F),          // tapicería roja
    'r' to Color(0xFF6B2F2F),          // tapicería en sombra
    'm' to Color(0xFF8A6A45),          // madera
    'v' to Color(0xFFD8A94A),          // cerveza
    'b' to Color(0xFF9FD8E8),          // espuma / vidrio
    'p' to Color(0xFFB05FA8),          // pantalla arcade
    'a' to Color(0xFF3E86A8),          // agua
    'c' to Color(0xFF6FB8D4),          // agua con brillo
    'B' to Color(0xFFD8D2C8),          // porcelana
    'y' to Color(0xFFD9A441),          // tela amarilla
)

val SPRITE_PLANTA by lazy { PixelSprite.of(PLANTA, palOficina) }
val SPRITE_RACK by lazy { PixelSprite.of(RACK, palOficina) }
val SPRITE_CAFE by lazy { PixelSprite.of(CAFE, palOficina) }
val SPRITE_ARCADE by lazy { PixelSprite.of(ARCADE, palOficina) }
val SPRITE_SOFA by lazy { PixelSprite.of(SOFA, palOficina) }
val SPRITE_TELE by lazy { PixelSprite.of(TELE, palOficina) }
val SPRITE_NEVERA by lazy { PixelSprite.of(NEVERA, palOficina) }
val SPRITE_MESA_OCIO by lazy { PixelSprite.of(MESA_OCIO, palOficina) }
val SPRITE_TUMBONA by lazy { PixelSprite.of(TUMBONA, palOficina) }
val SPRITE_SOMBRILLA by lazy { PixelSprite.of(SOMBRILLA, palOficina) }
val SPRITE_FLOTADOR by lazy { PixelSprite.of(FLOTADOR, palOficina) }
val SPRITE_CABINA by lazy { PixelSprite.of(CABINA, palOficina) }
val SPRITE_LAVABO by lazy { PixelSprite.of(LAVABO, palOficina) }
val SPRITE_ESTANTERIA by lazy { PixelSprite.of(ESTANTERIA, palOficina) }
val SPRITE_RELOJ by lazy { PixelSprite.of(RELOJ, palOficina) }
val SPRITE_BOLA by lazy { PixelSprite.of(BOLA, palOficina) }
val SPRITE_PIZARRA by lazy { PixelSprite.of(PIZARRA, palOficina) }

private val palIcono = mapOf('O' to NEGRO, 'L' to Color(0xFFFFD166))

val ICONO_IDEA by lazy { PixelSprite.of(ICO_IDEA, palIcono) }
val ICONO_ZZZ by lazy { PixelSprite.of(ICO_ZZZ, mapOf('O' to NEGRO)) }
val ICONO_CHAT by lazy { PixelSprite.of(ICO_CHAT, mapOf('O' to NEGRO, 'L' to BRILLO)) }
val ICONO_ERROR by lazy { PixelSprite.of(ICO_ERROR, mapOf('O' to NEGRO, 'L' to Color(0xFFE05252))) }

/**
 * Camisetas del equipo: paleta CURADA, no generada.
 *
 * Antes esto salía de un HSV con el tono al azar, y aparecían magentas y
 * azules eléctricos que no pertenecen a la identidad de Indaga: la sala se
 * veía "rara" aunque el dibujo estuviera bien. Estos ocho tonos son todos
 * vecinos del naranja de marca (terracotas, dorados, oliva, teal apagado):
 * distinguibles entre sí, pero de la misma familia cálida.
 */
private val CAMISETAS = listOf(
    Color(0xFFE07A3F),  // terracota
    Color(0xFFD4AF6A),  // dorado Indaga
    Color(0xFFA8763E),  // ocre
    Color(0xFF8C9A5B),  // oliva
    Color(0xFF4E8C7D),  // teal apagado
    Color(0xFFC1553F),  // ladrillo
    Color(0xFF6E7B8C),  // azul piedra
    Color(0xFFB98A5E),  // arena
)

/** Camiseta estable para un skill: mismo nombre ⇒ mismo color, siempre. */
fun colorDeSkill(nombre: String): Color {
    val i = (nombre.hashCode().toLong() and 0xFFFFFFFFL) % CAMISETAS.size
    return CAMISETAS[i.toInt()]
}

// Suelo y paredes en la paleta cálida de Indaga: antes eran grises parduzcos
// que no casaban con el resto de la app.
val ACENTO = NARANJA
val SUELO_A = Color(0xFF32281F)
val SUELO_B = Color(0xFF3B2F24)
val PARED = Color(0xFF191410)
val ZOCALO = Color(0xFF241C15)

// ── Atrezzo por oficio ──────────────────────────────────────────────────────
// Cada agente sostiene el objeto de su trabajo. Es lo que convierte a seis
// muñecos iguales en seis oficios distintos de un vistazo.

private const val P_CARPETA = """
.oooooooo..
.oMMMMMMoo.
.oMWWWWWMo.
.oMWWWWWMo.
.oMWWWWWMo.
.oMMMMMMMo.
.oooooooooo
"""

private const val P_TELEFONO = """
..oooooo..
.oWWWWWWo.
.oWGGGGWo.
.oWGGGGWo.
.oWGGGGWo.
.oWWWWWWo.
.oWWoooWo.
..oooooo..
"""

private const val P_LIBRETA = """
.oooooooo.
.oWWWWWWo.
.oWAAAAWo.
.oWWWWWWo.
.oWAAAAWo.
.oWWWWWWo.
.oWAAAAWo.
.oooooooo.
..oo......
.oLo......
"""

private const val P_ESCUDO = """
..oooooo..
.oAAAAAAo.
.oAWWWWAo.
.oAWAAWAo.
.oAWWWWAo.
.oAAAAAAo.
..oAAAAo..
...oAAo...
....oo....
"""

private const val P_GLOBO = """
...oooo...
..oGGGGo..
.oGWGGWGo.
.oGGWWGGo.
.oGWGGWGo.
..oGGGGo..
...oooo...
"""

private const val P_CALENDARIO = """
..o....o..
.oooooooo.
.oMMMMMMo.
.oWWWWWWo.
.oWAWAWWo.
.oWWWAWWo.
.oWAWWAWo.
.oooooooo.
"""

private const val P_TAZA = """
..........
.oooooo...
.oWWWWoo..
.oWWWWoWo.
.oWWWWoWo.
.oWWWWoo..
.oooooo...
..oooo....
"""

private val palProp = mapOf(
    'o' to NEGRO, 'O' to NEGRO,
    'M' to Color(0xFF8C6440),        // cartón / marco
    'W' to Color(0xFFE6DCCF),        // papel
    'G' to Color(0xFF2E5F73),        // pantalla / cristal
    'A' to NARANJA,                  // acento de marca
    'L' to Color(0xFF6E7B8C),        // lápiz
)

/** Objeto que sostiene cada agente según su oficio. */
enum class Oficio(val etiqueta: String, private val art: String) {
    NINGUNO("Sin objeto", ""),
    CARPETA("Carpeta", P_CARPETA),
    TELEFONO("Teléfono", P_TELEFONO),
    LIBRETA("Libreta", P_LIBRETA),
    ESCUDO("Escudo", P_ESCUDO),
    GLOBO("Mundo", P_GLOBO),
    CALENDARIO("Calendario", P_CALENDARIO),
    TAZA("Café", P_TAZA),
    ;

    val sprite: PixelSprite? by lazy {
        if (art.isBlank()) null else PixelSprite.of(art, palProp)
    }
}

/**
 * Oficio por defecto según el nombre del skill. Se acierta la mayoría de las
 * veces y evita que el usuario tenga que configurar los seis a mano.
 */
fun oficioPorNombre(nombre: String): Oficio {
    val n = nombre.lowercase()
    return when {
        "telefono" in n || "llamada" in n || "sms" in n -> Oficio.TELEFONO
        "lista" in n || "archivo" in n || "doc" in n -> Oficio.CARPETA
        "nota" in n || "diario" in n || "escri" in n -> Oficio.LIBRETA
        "antirrobo" in n || "segur" in n || "vigil" in n -> Oficio.ESCUDO
        "web" in n || "busca" in n || "internet" in n -> Oficio.GLOBO
        "agenda" in n || "record" in n || "calend" in n -> Oficio.CALENDARIO
        else -> Oficio.TAZA
    }
}

// ── Tipografía de píxel para el letrero de la sala ──────────────────────────
// Sólo las letras que hacen falta. Una fuente completa serían 40 glifos para
// escribir una palabra: aquí van siete.

private val LETRAS: Map<Char, String> = mapOf(
    'D' to """
AAAA.
A...A
A...A
A...A
A...A
A...A
AAAA.
""",
    'C' to """
.AAA.
A...A
A....
A....
A....
A...A
.AAA.
""",
    'A' to """
.AAA.
A...A
A...A
AAAAA
A...A
A...A
A...A
""",
    'G' to """
.AAA.
A...A
A....
A.AAA
A...A
A...A
.AAA.
""",
    'E' to """
AAAAA
A....
A....
AAAA.
A....
A....
AAAAA
""",
    'N' to """
A...A
AA..A
A.A.A
A.A.A
A..AA
A...A
A...A
""",
    'T' to """
AAAAA
..A..
..A..
..A..
..A..
..A..
..A..
""",
    'O' to """
.AAA.
A...A
A...A
A...A
A...A
A...A
.AAA.
""",
    'S' to """
.AAAA
A....
A....
.AAA.
....A
....A
AAAA.
""",
)

/** Renderiza una palabra como un solo sprite. Devuelve null si falta un glifo. */
fun textoPixel(palabra: String, color: Color): PixelSprite? {
    val glifos = palabra.uppercase().map { LETRAS[it] ?: return null }
    val pal = mapOf('A' to color)
    val filas = glifos.map { it.trimIndent().lines().filter(String::isNotBlank) }
    val alto = filas.maxOf { it.size }
    val sep = 1
    val ancho = filas.sumOf { f -> f.maxOf { it.length } } + sep * (filas.size - 1)

    val lienzo = MutableList(alto) { StringBuilder() }
    filas.forEachIndexed { i, glifo ->
        val w = glifo.maxOf { it.length }
        for (y in 0 until alto) {
            lienzo[y].append((glifo.getOrNull(y) ?: "").padEnd(w, '.'))
            if (i < filas.size - 1) lienzo[y].append(".".repeat(sep))
        }
    }
    return PixelSprite.of(lienzo.joinToString("\n") { it.toString() }, pal)
}
